In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.graph_objects as go
import plotly.express as px

In [2]:
url = "games.csv"
juegos = pd.read_csv(url)

In [3]:
juegos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1512 entries, 0 to 1511
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         1512 non-null   int64
 1   Title              1512 non-null   object
 2   Release Date       1512 non-null   object
 3   Team               1511 non-null   object
 4   Rating             1499 non-null   float64
 5   Times Listed       1512 non-null   object
 6   Number of Reviews  1512 non-null   object
 7   Genres             1512 non-null   object
 8   Summary            1511 non-null   object
 9   Reviews            1512 non-null   object
 10  Plays              1512 non-null   object
 11  Playing            1512 non-null   object
 12  Backlogs           1512 non-null   object
 13  Wishlist           1512 non-null   object
dtypes: float64(1), int64(1), object(12)
memory usage: 165.5+ KB

Eliminar= Unnamed 0, , summary, backlogs, wishlist
Rename =plays, jugadorestotal, playing, jugadoresactuales

In [4]:

juegos.drop(columns=["Unnamed: 0", "Summary", "Backlogs","Wishlist"], inplace=True)

In [5]:
juegos.drop(columns=["Reviews"], inplace=True)

In [6]:
juegos.rename(columns={"Title":"titulo", "Release Date":"fecha_de_lanzamiento", "Team":"equipo", "Rating":"calificacion","Times Listed":"veces_mencionadas","Number of Reviews":"numero_de_resenas","Genres":"generos","Plays":"jugadores_totales","Playing":"jugadores_activos"}, inplace=True)

In [7]:
juegos.head()

,titulo,fecha_de_lanzamiento,equipo,calificacion,veces_mencionadas,numero_de_resenas,generos,jugadores_totales,jugadores_activos
0,Elden Ring,"Feb 25, 2022","['Bandai Namco Entertainment', 'FromSoftware']",4.5,3.9K,3.9K,"['Adventure', 'RPG']",17K,3.8K
1,Hades,"Dec 10, 2019",['Supergiant Games'],4.3,2.9K,2.9K,"['Adventure', 'Brawler', 'Indie', 'RPG']",21K,3.2K
2,The Legend of Zelda: Breath of the Wild,"Mar 03, 2017","['Nintendo', 'Nintendo EPD Production Group No...",4.4,4.3K,4.3K,"['Adventure', 'RPG']",30K,2.5K
3,Undertale,"Sep 15, 2015","['tobyfox', '8-4']",4.2,3.5K,3.5K,"['Adventure', 'Indie', 'RPG', 'Turn Based Stra...",28K,679
4,Hollow Knight,"Feb 24, 2017",['Team Cherry'],4.4,3K,3K,"['Adventure', 'Indie', 'Platform']",21K,2.4K

In [13]:
juegos.loc[juegos['titulo'] == "Hades"]

,titulo,fecha_de_lanzamiento,equipo,calificacion,veces_mencionadas,numero_de_resenas,generos,jugadores_totales,jugadores_activos
1,Hades,"Dec 10, 2019",['Supergiant Games'],4.3,2.9K,2.9K,"['Adventure', 'Brawler', 'Indie', 'RPG']",21K,3.2K
327,Hades,"Dec 10, 2019",['Supergiant Games'],4.3,2.9K,2.9K,"['Adventure', 'Brawler', 'Indie', 'RPG']",21K,3.2K
777,Hades,"Dec 10, 2019",['Supergiant Games'],4.3,2.9K,2.9K,"['Adventure', 'Brawler', 'Indie', 'RPG']",21K,3.2K

In [10]:
juegos_duplicados = juegos.duplicated()
print(juegos[juegos_duplicados])

                                       titulo fecha_de_lanzamiento  \
326                                Elden Ring         Feb 25, 2022
327                                     Hades         Dec 10, 2019
328   The Legend of Zelda: Breath of the Wild         Mar 03, 2017
329                                 Undertale         Sep 15, 2015
330                             Hollow Knight         Feb 24, 2017
...                                       ...                  ...
1268          Bloodstained: Curse of the Moon         May 23, 2018
1269                     Final Fantasy XIII-2         Dec 15, 2011
1270                                  Agar.io         Apr 28, 2015
1271        Fatal Frame II: Crimson Butterfly         Nov 27, 2003
1496                                  FIFA 13         Sep 25, 2012

                                                 equipo  calificacion  \
326      ['Bandai Namco Entertainment', 'FromSoftware']           4.5
327                                ['Supergiant Games']           4.3
328   ['Nintendo', 'Nintendo EPD Production Group No...           4.4
329                                  ['tobyfox', '8-4']           4.2
330                                     ['Team Cherry']           4.4
...                                                 ...           ...
1268                                   ['Inti Creates']           3.6
1269                                    ['Square Enix']           3.3
1270              ['Miniclip.com', 'Matheus Valadares']           2.2
1271       ['Tecmo Co., Ltd.', 'Ubisoft Entertainment']           4.2
1496                   ['Electronic Arts', 'EA Canada']           3.2

     veces_mencionadas numero_de_resenas  \
326               3.9K              3.9K
327               2.9K              2.9K
328               4.3K              4.3K
329               3.5K              3.5K
330                 3K                3K
...                ...               ...
1268               341               341
1269               482               482
1270                81                81
1271               398               398
1496                62                62

                                                generos jugadores_totales  \
326                                ['Adventure', 'RPG']               17K
327            ['Adventure', 'Brawler', 'Indie', 'RPG']               21K
328                                ['Adventure', 'RPG']               30K
329   ['Adventure', 'Indie', 'RPG', 'Turn Based Stra...               28K
330                  ['Adventure', 'Indie', 'Platform']               21K
...                                                 ...               ...
1268                 ['Adventure', 'Indie', 'Platform']              2.3K
1269                               ['Adventure', 'RPG']              2.3K
1270                              ['Indie', 'Strategy']              4.4K
1271                                      ['Adventure']                1K
1496                             ['Simulator', 'Sport']              1.6K

     jugadores_activos
326               3.8K
327               3.2K
328               2.5K
329                679
330               2.4K
...                ...
1268                41
1269                58
1270                 8
1271                38
1496                 2

[393 rows x 9 columns]

In [14]:
juegos.drop_duplicates(inplace=True)

In [23]:
juegos.isnull().sum()

titulo                  0
fecha_de_lanzamiento    0
equipo                  0
calificacion            0
veces_mencionadas       0
numero_de_resenas       0
generos                 0
jugadores_totales       0
jugadores_activos       0
dtype: int64

In [19]:
juegos.loc[juegos['equipo'].isnull()]

Empty DataFrame
Columns: [titulo, fecha_de_lanzamiento, equipo, calificacion, veces_mencionadas, numero_de_resenas, generos, jugadores_totales, jugadores_activos]
Index: []

In [18]:
juegos['equipo'].fillna("Hitsuji", inplace=True)

C:\Users\twoem\AppData\Local\Temp\ipykernel_16988\2762928740.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  juegos['equipo'].fillna("Hitsuji", inplace=True)

In [22]:
juegos.loc[juegos["calificacion"].isnull()]

Empty DataFrame
Columns: [titulo, fecha_de_lanzamiento, equipo, calificacion, veces_mencionadas, numero_de_resenas, generos, jugadores_totales, jugadores_activos]
Index: []

In [21]:
juegos.dropna(subset=["calificacion"], inplace=True)